#@Cart.Api_HostAddress = grpcs://localhost:6052/cart.Cart/
@Cart.Api_HostAddress = grpcs://localhost:5052/cart.Cart/
@auth_token = "" # call auth api before


GRPC grpcs://localhost:6052/cart.Cart/SayHello

{
    "name": "HTTP Client with gRPC"
}

###
GRPC {{Cart.Api_HostAddress}}GetList

{
    "cartId": "36f0b165-a594-4fa7-b1be-9eb5326315ff"
}

###
GRPC {{Cart.Api_HostAddress}}GetListStream

{
    "cartId": "36f0b165-a594-4fa7-b1be-9eb5326315ff"
}
