@Catalog.Api_HostAddress = http://localhost:5229

GET {{Catalog.Api_HostAddress}}/api/categories
Accept: application/json

###

POST {{Catalog.Api_HostAddress}}/api/categories
Content-Type: application/json

{
  "name": "Test",
  "image": null,
  "parentCategory": null
}

### get products
GET {{Catalog.Api_HostAddress}}/api/products
Accept: application/json


### create product
POST {{Catalog.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "testProduct",
  "description": "testProduct long Description",
  "image": null,
  "price": 100,
  "amount": 500,
  "category": "Test"
}


