version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_management
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge