version: '3'

services:
    gateway:
        build:
            context: ./
            dockerfile: ./Gateway.Api/Dockerfile
        environment:
            - RabbitSettings__Host=rabbitmq_management
    cart-api:
      build:
          context: ./
          dockerfile: ./Cart.Api/Dockerfile
      environment:
          - RabbitSettings__Host=rabbitmq_management
          - LiteDbOptions__DatabaseLocation=lite_main.db
    catalog-api:
      build:
          context: ./
          dockerfile: ./Catalog.Api/Dockerfile
      environment:
          - RabbitSettings__Host=rabbitmq_management
          - ConnectionStrings__CatalogContext=Data Source=sql_main.db

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq_management
        environment:
          - RABBITMQ_DEFAULT_USER=test
          - RABBITMQ_DEFAULT_PASS=test
        ports:
          - "5672:5672"
          - "15672:15672"

    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak_dev
        environment:
          - KC_BOOTSTRAP_ADMIN_USERNAME=admin
          - KC_BOOTSTRAP_ADMIN_PASSWORD=change_me
        command:
          - start-dev
        ports:
          - "8080:8080"

networks:
  default:
    driver: bridge
