@Gateway.Api_HostAddress = http://localhost:5152

### Products
GET {{Gateway.Api_HostAddress}}/api/v1/products/
Accept: application/json

###

GET {{Gateway.Api_HostAddress}}/api/v1/productDetails/1
Accept: application/json

###

GET {{Gateway.Api_HostAddress}}/api/v1/products-details/1
Accept: application/json

###

GET {{Gateway.Api_HostAddress}}/api/v1/categories
Accept: application/json
